### ISSUE TITLE
Computation of the area of reachable sets?

### ISSUE THREAD

**Issue by thomasjlew** [neu-autonomy/nfl_veripy#1]
Hi, thanks for the great work and open-sourcing this code!

With 2d inputs, the area function in scipy.spatial.ConvexHull returns the perimeter of the convex hull. Perhaps this line

https://github.com/mit-acl/nn_robustness_analysis/blob/cff947c1b6c6b586a004d13387bb2fe31131dcab/nn_closed_loop/nn_closed_loop/partitioners/ClosedLoopPartitioner.py#L108

should be changed to `estimated_area = estimated_hull.volume` ?

**Comment by mfe7** [comment]
Hey, great catch! Looks like [others have fallen into this trap too :/](https://stackoverflow.com/questions/35664675/in-scipys-convexhull-what-does-area-measure#comment70420675_35666769).

At first glance this only seems to impacts the case of polytope sets, which we didn't play around with much during development. I'll push a fix and also look a little deeper to double check that it doesn't affect things in other places.

**Comment by thomasjlew** [comment]
Yes I agree, it's easy to fall in this trap! I think this is only used to compute the reachable set estimation error and compare different approaches, so it should not make a big difference and should not affect your proposed algorithms.

**Comment by mfe7** [comment]
finally made this change in 5492b1f76765c9aba87d4c5d1a638c0752f86e30.

And for anyone reading this, I recommend checking out Thomas' great recent paper on reachability analysis! https://arxiv.org/pdf/2112.05745.pdf
